% -------------------------------------------------------------------
%  Generated by MATLAB on 11-Feb-2022 13:35:20
%  MATLAB version: 9.9.0.1495850 (R2020b) Update 1
% -------------------------------------------------------------------
saveVarsMat = load('tapered_aed_curves.mat');

all_dose_curves = saveVarsMat.all_dose_curves; % <1x12 cell> too many elements at all_dose_curves{1}{1}

all_med_names = cell(1, 12);
all_med_names{1} = cell(3, 1);
all_med_names{1}{1,1} = 'clobazam';
all_med_names{1}{2,1} = 'lacosamide';
all_med_names{1}{3,1} = 'lorazepam';
all_med_names{2} = cell(4, 1);
all_med_names{2}{1,1} = 'carbamazepine';
all_med_names{2}{2,1} = 'levetiracetam';
all_med_names{2}{3,1} = 'lorazepam';
all_med_names{2}{4,1} = 'topiramate';
all_med_names{3} = cell(4, 1);
all_med_names{3}{1,1} = 'clobazam';
all_med_names{3}{2,1} = 'clonazepam';
all_med_names{3}{3,1} = 'levetiracetam';
all_med_names{3}{4,1} = 'lorazepam';
all_med_names{4} = cell(6, 1);
all_med_names{4}{1,1} = 'clobazam';
all_med_names{4}{2,1} = 'eslicarbazepine';
all_med_names{4}{3,1} = 'lamotrigine';
all_med_names{4}{4,1} = 'levetiracetam';
all_med_names{4}{5,1} = 'lorazepam';
all_med_names{4}{6,1} = 'oxcarbazepine';
all_med_names{5} = cell(5, 1);
all_med_names{5}{1,1} = 'clobazam';
all_med_names{5}{2,1} = 'eslicarbazepine';
all_med_names{5}{3,1} = 'levetiracetam';
all_med_names{5}{4,1} = 'lorazepam';
all_med_names{5}{5,1} = 'white';
all_med_names{6} = cell(4, 1);
all_med_names{6}{1,1} = 'levetiracetam';
all_med_names{6}{2,1} = 'lorazepam';
all_med_names{6}{3,1} = 'pregabalin';
all_med_names{6}{4,1} = 'white';
all_med_names{7} = cell(4, 1);
all_med_names{7}{1,1} = 'carbamazepine';
all_med_names{7}{2,1} = 'clobazam';
all_med_names{7}{3,1} = 'levetiracetam';
all_med_names{7}{4,1} = 'lorazepam';
all_med_names{8} = cell(5, 1);
all_med_names{8}{1,1} = 'clobazam';
all_med_names{8}{2,1} = 'lamotrigine';
all_med_names{8}{3,1} = 'levetiracetam';
all_med_names{8}{4,1} = 'lorazepam';
all_med_names{8}{5,1} = 'oxcarbazepine';
all_med_names{9} = cell(4, 1);
all_med_names{9}{1,1} = 'lamotrigine';
all_med_names{9}{2,1} = 'levetiracetam';
all_med_names{9}{3,1} = 'lorazepam';
all_med_names{9}{4,1} = 'topiramate';
all_med_names{10} = cell(3, 1);
all_med_names{10}{1,1} = 'lamotrigine';
all_med_names{10}{2,1} = 'lorazepam';
all_med_names{10}{3,1} = 'zonisamide';
all_med_names{11} = cell(5, 1);
all_med_names{11}{1,1} = 'clobazam';
all_med_names{11}{2,1} = 'clonazepam';
all_med_names{11}{3,1} = 'lacosamide';
all_med_names{11}{4,1} = 'levetiracetam';
all_med_names{11}{5,1} = 'lorazepam';
all_med_names{12} = cell(4, 1);
all_med_names{12}{1,1} = 'clobazam';
all_med_names{12}{2,1} = 'levetiracetam';
all_med_names{12}{3,1} = 'lorazepam';
all_med_names{12}{4,1} = 'valproic acid';

all_tHr = saveVarsMat.all_tHr; % <1x12 cell> too many elements at all_tHr{1}{1}

ans = 11;

cohort_info = saveVarsMat.cohort_info; % <1x1 table> unsupported class

dDose = [-20; 10; -10; 0; 0; 20; -20; 20; -20; 20; -20];

dose_curve = [16.896715097915351; 16.896715097915351; 16.896715097915351; ...
              16.544535691724569; 16.544535691724569; 16.6708780795957; ...
              18.359128237523681; 17.275742261528734; 17.275742261528734; ...
              18.359128237523681; 18.359128237523681; 19.92103600758054; ...
              ];

emu_days = [10; 9; 9; 8; 8; 7; 3; 2; 2; 1; 1; 0];

emu_dur = [264 240 432 264 432 240 312 312 264 264 240 384];

hrs = [24; 24; 72; 72; 120; 216; 144; 192; 216];

i = 12;

ieeg_offset = saveVarsMat.ieeg_offset; % <3x12 cell> unsupported class at ieeg_offset{3,1}

max_dur = 450;

med_name_ind = logical([1; 0; 0]);

med_names = cell(4, 1);
med_names{1,1} = 'clobazam';
med_names{2,1} = 'levetiracetam';
med_names{3,1} = 'lorazepam';
med_names{4,1} = 'valproic acid';

meds = saveVarsMat.meds; % <1x1 table> unsupported class

n = 1;

p = [0.05981522425773874 -0.41535060012634617 17.25225047378396];

ptID = 'HUP190';

ptIDs = cell(12, 1);
ptIDs{1,1} = 'HUP140';
ptIDs{2,1} = 'HUP144';
ptIDs{3,1} = 'HUP146';
ptIDs{4,1} = 'HUP157';
ptIDs{5,1} = 'HUP160';
ptIDs{6,1} = 'HUP164';
ptIDs{7,1} = 'HUP166';
ptIDs{8,1} = 'HUP173';
ptIDs{9,1} = 'HUP177';
ptIDs{10,1} = 'HUP181';
ptIDs{11,1} = 'HUP187';
ptIDs{12,1} = 'HUP190';

taper_info = [];

tdrug = 10;

this_med_info = saveVarsMat.this_med_info; % <1x1 table> unsupported class

x = [1; 1; 2; 2; 3; 7; 8; 8; 9; 9; 10];

y = [30; 10; 20; 10; 10; 10; 30; 10; 30; 10; 30; 10];

clear saveVarsMat;
